### ISSUE TITLE
Could you document what each column of the probability array corresponds to?

### ISSUE THREAD

**Issue by dvg-p4** [jeremymcrae/bgen#6]
I'm guessing from experimentation that the probabilities for phased data are P(0|-), P(1|-), P(-|0), P(-|1), but it would be nice to have this clarified.

**Comment by jeremymcrae** [comment]
I'm not sure of your notation, I would describe the columns for phased probabilities as the first two probabilities are for the first haplotype (for allele 1 and allele 2), and the last two columns are for the second haplotype (again, allele 1, allele 2). There's a formal description in the bgen format spec: https://www.chg.ox.ac.uk/~gav/bgen_format/spec/latest.html, although that describes probabilities as stored in the bgen, which omits the last probability per haplotype since it can be computed from the other states.

Also, this is only true for biallelic diploid variants, variants with more alleles, or samples with different ploidy will differ. I've updated the readme to describe the probabilities array for biallelic diploid variants, which should be what most people will encounter.

**Comment by dvg-p4** [comment]
Thank you, that addition makes it a lot clearer! I think I had the right idea, though I couldn't quite figure out how to notate it--what you put in the readme is a lot better.
